name: AI Auto Merge
on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]

jobs:
  auto-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const runs = await github.rest.actions.listWorkflowRunPullRequests({
              owner, repo, run_id: context.payload.workflow_run.id
            });
            for (const pr of runs.data.pull_requests) {
              // 条件: ブランチとラベルと作者
              const { data: full } = await github.rest.pulls.get({ owner, repo, pull_number: pr.number });
              const labels = (full.labels||[]).map(l=>l.name);
              if (!full.head.ref.startsWith('ai/')) continue;
              if (!labels.includes('ai/automerge')) continue;
              // ここで必要なら作者や変更パスをチェックして厳格化
              await github.rest.pulls.merge({
                owner, repo, pull_number: pr.number,
                merge_method: 'squash'
              });
            }
