name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app
        ports: [ "3306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql, dom, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          cp .env.example .env
          php -r "file_put_contents('.env', str_replace('DB_PASSWORD=', 'DB_PASSWORD=root', file_get_contents('.env')));"
          php artisan key:generate

      - name: Wait for DB
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/3306) && break || sleep 2
          done

      - name: **Fail if BIGINT is used (Access ODBC incompatible)**
        run: |
          if grep -RniE "bigInteger|bigIncrements" database/migrations; then
            echo "BIGINT detected in migrations. Use INT only for Access ODBC compatibility."
            exit 1
          fi

      - name: Run migrations
        run: php artisan migrate --force

      - name: Lint (Pint)
        run: vendor/bin/pint --test

      - name: Static Analysis (PHPStan/Larastan)
        run: vendor/bin/phpstan analyse --memory-limit=1G

      - name: PHPUnit
        run: vendor/bin/phpunit --testsuite Unit,Feature
