name: Label AI PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'ai/')
        with:
          labels: ai/automerge
